### ISSUE TITLE
How to active these check in .eslintrc

### ISSUE THREAD

**Issue by MattSeen** [burnnat/eslint-plugin-extjs#3]
Hi,

I'm new to ExtJS and Eslint. I'm trying to get the rules you've written to work with my install of eslint.

eslint --version: v0.24.1

I'm using the .eslintrc reset file from here: http://bl.ocks.org/cletusw/e01a85e399ab563b1236

And including your rules as follows:

``` javascript
{
  ...etc

  "rules": {
    ...etc

    ////////// EXTJS //////////
    "ext-array-foreach": 0,
    "ext-deps": 0,
    "no-ext-create": 0,
    "no-ext-multi-def": 0
  }
}
```

Is this correct? Do I set these key values to 0 to activate the checks? I see in the index.js file you are specifying the rulesConfig with the various rules and key values, 0 in your case. The reason I ask is I have a sample file with some invalid array foreach loops and it doesn't seem to enforce the checks you have created?

Any help you can provide would be greatly appreciated.

Kind Regards,
- Matt

**Comment by burnnat** [comment]
Hi Matt, looks like you have a few issues here. First off, you didn't mention how you installed the `eslint-plugin-extjs` package, but you may want to double-check because if `eslint` is installed globally, then `eslint-plugin-extjs` will need to be installed globally as well. From the [ESLint documentation](http://eslint.org/docs/user-guide/configuring#configuring-plugins):

> **Note:** A globally-installed instance of ESLint can only use globally-installed ESLint plugins. A locally-installed ESLint can make sure of both locally- and globally- installed ESLint plugins.

Also in your `.eslintrc` you'll need to add the plugin name before each rule:

> To configure a rule which is defined within a plugin you have to prefix the rule ID with the plugin name and a `/`.

So the end result should look something like this (in addition to your other rules and settings):

```
{
    "plugins": ["extjs"],
    "rules": {
        "extjs/ext-array-foreach": 2
    }
}
```

Note that for ESLint rules, a value of `0` means the rule is disabled, `1` means it's treated as a warning, and `2` means it's treated as an error, so make sure any rules you want enabled are set to either `1` or `2` (since as you note, all the extjs rules are set to be disabled by default).

Hope this helps!

**Comment by MattSeen** [comment]
Hi @burnnat,

Thanks for getting back to me so quickly! I installed your plugin globally along with eslint (I'm also using it with SublimeLinter-contrib-eslint).

I made sure to namespace the rules and set them to warnings and everything is working just fine!

Thanks again.
- Matthew
